package com.openminis.app.tools

import android.content.Context
import com.openminis.app.data.model.AgentToolDefinition
import com.openminis.app.data.model.AgentToolParam
import com.openminis.app.logging.AppLogger
import com.openminis.app.sandbox.PRootKernel
import com.openminis.app.sandbox.ShellExecutor
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.sync.withLock
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.util.concurrent.ConcurrentHashMap

/**
 * [T-py-meta-tools] Registry of agent-minted Python tools ("pytools").
 *
 * Port of Zafiro's PyMetaToolsBuiltin + CustomPyToolRegistry (architecture,
 * not code — Zafiro ships no LICENSE). Each tool is a Python source defining
 * `main(**kwargs)`; parameters come from basic type annotations on main
 * (str/int/float/bool), the docstring becomes the description. The schema is
 * generated by introspecting the code via the in-PRoot harness
 * (/usr/local/lib/minis-pytools/harness.py, shipped via default_mount).
 *
 * Storage is GLOBAL (filesDir/minis-global/meta-tools/, bind-mounted at
 * /var/minis/meta-tools) so a tool minted in one session is callable in
 * every later session — same lifetime as skills and memory. registry.json
 * holds metadata; <name>.py holds the code beside it.
 *
 * The in-turn hot-registration mechanism (Zafiro D20) is free here: the
 * agentTools computed property reads [definitions] on every turn, so a
 * successful write that refreshes the cache makes the new tool visible to
 * the NEXT model request in the SAME conversation — no restart, no
 * app update. That is the whole point of the feature: the agent can add its
 * own missing tool mid-task.
 *
 * Trust model: pytools execute with the same PRoot privileges the agent
 * already has via shell_execute — a pytool is persisted code, not a new
 * privilege. The registry write validates (introspection round-trip) and
 * refuses invalid tools with a fixable error message; nothing is saved
 * unless introspection passes (fail-closed).
 */
object PyMetaToolStore {

    private const val TAG = "PyMetaTools"
    private const val REGISTRY_FILE = "registry.json"
    private const val DRAFT_NAME = ".draft.py"

    /**
     * Serializes write operations: the draft slot is a single shared file, so
     * two concurrent writes (two sessions minting at once) could overwrite
     * each other's draft mid-introspection — the introspection would then
     * validate code A and persist code B. One lock around the whole
     * validate-and-persist flow keeps the draft private to its writer.
     */
    private val writeMutex = kotlinx.coroutines.sync.Mutex()

    /** PRoot-visible dir (bind-mounted from filesDir/minis-global/meta-tools). */
    const val LINUX_DIR = "/var/minis/meta-tools"

    /** Default per-tool execution timeout. Max hard-capped below. */
    const val DEFAULT_TIMEOUT_S = 60
    const val MAX_TIMEOUT_S = 300

    private val NAME_REGEX = Regex("^[a-z][a-z0-9_]{2,31}$")

    /** Builtin tool names a pytool must never shadow. */
    val RESERVED_NAMES: Set<String> = setOf(
        "shell_execute", "file_read", "file_write", "file_edit", "read_image",
        "browser_use", "memory_write", "memory_get", "spawn_agent", "agent_status",
        "wait_and_resume", "timer_list", "timer_cancel", "keep_alive",
        "job_start", "job_poll", "job_kill", "ask_user", "lan_share",
        "web_fetch", "web_search", "ocr_read", "event_rule_set", "event_rule_list",
        "event_rule_delete", "event_emit", "project_create", "project_list",
        "project_delete", "marketplace_browse", "marketplace_entry",
        "marketplace_install", "plugin_install", "plugin_list", "plugin_uninstall",
        "plugin_manifest_schema", "plugin_doctor", "plugin_reinstall",
        "plugin_reinstall_from_registry", "plugin_enable", "py_meta_tools",
        "android_alarm", "android_calendar", "android_clipboard", "android_contacts",
    )

    // -- Data types --

    data class PyTool(
        val name: String,
        val description: String,
        val schema: JSONObject,
        val timeoutSeconds: Int = DEFAULT_TIMEOUT_S,
        val isEnabled: Boolean = true,
        val createdAt: Long = System.currentTimeMillis(),
        val updatedAt: Long = System.currentTimeMillis(),
    )

    sealed class WriteResult {
        data class Success(val tool: PyTool) : WriteResult()
        data class Invalid(val message: String) : WriteResult()
        data class Error(val message: String) : WriteResult()
    }

    // -- State --

    private val _tools = MutableStateFlow<List<PyTool>>(emptyList())
    val tools: StateFlow<List<PyTool>> = _tools.asStateFlow()

    /** Cheap per-call registry cache: name → tool. Rebuilt on reload(). */
    private val cache = ConcurrentHashMap<String, PyTool>()

    @Volatile
    private var appContext: Context? = null

    fun init(context: Context) {
        appContext = context.applicationContext
        runCatching { reload() }.onFailure {
            AppLogger.warning(TAG, "reload failed — continuing with ${_tools.value.size} tool(s): ${it.message}")
        }
    }

    private fun toolsDir(context: Context): File =
        File(context.filesDir, "minis-global/meta-tools")

    /** Host file for a tool's code. */
    fun codeFile(context: Context, name: String): File =
        File(toolsDir(context), "$name.py")

    // -- Introspection (via the in-PRoot harness) --

    /**
     * Introspect [code] (a draft not yet saved) by writing it to the draft
     * slot and running the harness against it. Returns the parsed
     * {"ok": true, description, schema} payload or a failure message.
     */
    private suspend fun introspectDraft(context: Context, code: String): Pair<JSONObject?, String?> {
        val dir = toolsDir(context)
        dir.mkdirs()
        val draft = File(dir, DRAFT_NAME)
        try {
            draft.writeText(code)
            val result = ShellExecutor.execute(
                context = context,
                command = "python3 /usr/local/lib/minis-pytools/harness.py introspect $LINUX_DIR/$DRAFT_NAME",
                timeout = 30_000L,
            )
            val out = result.output.trim()
            if (!out.startsWith("{")) {
                return null to "Introspection failed (exit ${result.exitCode}): " +
                    out.take(400).ifBlank { "no output" }
            }
            val parsed = runCatching { JSONObject(out) }.getOrNull()
                ?: return null to "Introspection returned invalid JSON: ${out.take(200)}"
            if (!parsed.optBoolean("ok", false)) {
                val line = parsed.optInt("line", -1)
                val lineNote = if (line > 0) " (line $line)" else ""
                return null to "${parsed.optString("error", "INVALID")}$lineNote: " +
                    parsed.optString("message", "Tool rejected by introspection.")
            }
            return parsed to null
        } catch (t: Throwable) {
            if (t.message?.contains("PRootKernel must be booted") == true) {
                return null to "Sandbox not booted yet — retry in a moment."
            }
            return null to "Introspection error: ${t.message ?: t::class.java.simpleName}"
        } finally {
            draft.delete()
        }
    }

    // -- CRUD --

    /**
     * Create or replace a tool. Runs the introspection round-trip first;
     * nothing is persisted unless it passes (fail-closed). A successful write
     * refreshes the registry cache so [definitions] — read fresh every agent
     * turn via the agentTools computed property — exposes the tool to the
     * NEXT model request in the same conversation (D20 hot registration).
     */
    suspend fun write(
        context: Context,
        name: String,
        code: String,
        description: String?,
        timeoutSeconds: Int?,
        enabled: Boolean,
    ): WriteResult = writeMutex.withLock {
        writeLocked(context, name, code, description, timeoutSeconds, enabled)
    }

    private suspend fun writeLocked(
        context: Context,
        name: String,
        code: String,
        description: String?,
        timeoutSeconds: Int?,
        enabled: Boolean,
    ): WriteResult {
        val nameError = validateName(name)
        if (nameError != null) {
            return WriteResult.Invalid(nameError)
        }
        val trimmed = name.trim()
        if (code.isBlank()) {
            return WriteResult.Invalid("Tool code is empty. The code must define main(...) — parameters from basic type annotations (str/int/float/bool), the docstring becomes the description.")
        }
        if (!code.contains("def main")) {
            return WriteResult.Invalid(
                "Tool code must define a callable main(...). Parameters come from basic type " +
                    "annotations on main (str/int/float/bool) and the docstring becomes the description.",
            )
        }
        val timeout = (timeoutSeconds ?: DEFAULT_TIMEOUT_S).coerceIn(5, MAX_TIMEOUT_S)

        val (introspection, error) = introspectDraft(context, code)
        if (introspection == null) {
            return WriteResult.Invalid(error ?: "Introspection failed.")
        }

        val finalDescription = description?.takeIf { it.isNotBlank() }
            ?: introspection.optString("description", "").ifBlank { "Agent-defined Python tool." }
        val schema = introspection.optJSONObject("schema") ?: JSONObject()

        val dir = toolsDir(context)
        dir.mkdirs()
        val existing = cache[trimmed]
        val tool = PyTool(
            name = trimmed,
            description = finalDescription.take(500),
            schema = schema,
            timeoutSeconds = timeout,
            isEnabled = enabled,
            createdAt = existing?.createdAt ?: System.currentTimeMillis(),
            updatedAt = System.currentTimeMillis(),
        )
        return try {
            codeFile(context, trimmed).writeText(code)
            upsertRegistry(context, tool)
            cache[trimmed] = tool
            _tools.value = _tools.value.filter { it.name != trimmed } + tool
            AppLogger.info(TAG, "pytool registered (hot): name=$trimmed schema=${schema.length()} chars")
            WriteResult.Success(tool)
        } catch (t: Throwable) {
            WriteResult.Error("Failed to persist tool: ${t.message ?: t::class.java.simpleName}")
        }
    }

    fun get(name: String): PyTool? = cache[name]

    fun delete(context: Context, name: String): Boolean {
        val trimmed = name.trim()
        if (!cache.containsKey(trimmed)) return false
        val removed = runCatching {
            codeFile(context, trimmed).delete()
            removeFromRegistry(context, trimmed)
        }.getOrDefault(false)
        cache.remove(trimmed)
        _tools.value = _tools.value.filter { it.name != trimmed }
        return removed
    }

    /** AgentToolDefinitions for all ENABLED tools — appended to the agent tool surface. */
    fun definitions(): List<AgentToolDefinition> =
        _tools.value.filter { it.isEnabled }.map { it.toDefinition() }

    /**
     * Test-only entry point: convert one tool through the same code path
     * definitions() uses. Internal so the JVM test suite can verify the
     * schema conversion without Robolectric.
     */
    internal fun definitionsForTest(tool: PyTool): AgentToolDefinition = tool.toDefinition()

    private fun PyTool.toDefinition(): AgentToolDefinition {
        val props = schema.optJSONObject("properties") ?: JSONObject()
        val required = schema.optJSONArray("required") ?: JSONArray()
        val params = LinkedHashMap<String, AgentToolParam>()
        val ordering = mutableListOf<String>()
        val keys = props.keys().asSequence().toList()
        // Required params first, then the rest in declaration order — matches
        // how every other Minis X tool orders its schema.
        val requiredSet = (0 until required.length()).map { required.optString(it) }.toSet()
        (requiredSet + keys.filter { it !in requiredSet }).forEach { key ->
            val prop = props.optJSONObject(key) ?: return@forEach
            val type = prop.optString("type", "string")
            var desc = prop.optString("description", "")
            if (desc.startsWith("default: ")) desc = "Optional. $desc"
            params[key] = AgentToolParam(type, desc.ifBlank { "Parameter $key." })
            ordering.add(key)
        }
        return AgentToolDefinition(
            name = name,
            description = "$description (agent-defined Python tool; runs via the minis-pytools harness.)",
            parameters = params,
            required = ordering.filter { it in requiredSet },
            propertyOrdering = ordering,
        )
    }

    // -- Registry persistence --

    private fun registryFile(context: Context): File =
        File(toolsDir(context), REGISTRY_FILE)

    // -- Pure helpers (JVM-testable — no Robolectric in this module) --

    /**
     * Validate a tool name. Returns null when valid, else the reason.
     * Pure so the name rules (the part that gates the registry) run on the JVM.
     */
    fun validateName(name: String): String? {
        val trimmed = name.trim()
        if (!NAME_REGEX.matches(trimmed)) {
            return "Invalid tool name '$trimmed'. Names are 3-32 chars: lowercase letters, digits, " +
                "underscores, must start with a letter (e.g. fetch_weather)."
        }
        if (trimmed in RESERVED_NAMES) {
            return "'$trimmed' is a reserved builtin tool name — pick a different name. " +
                "This is a hard policy boundary, not a transient failure; do not retry with the same name."
        }
        return null
    }

    /**
     * Parse a registry.json body into tools. Malformed entries are skipped,
     * not fatal — degrading to "some tools missing" always beats a store
     * that cannot load (the SkillRepository GH#147 lesson).
     */
    fun parseRegistry(body: String): List<PyTool> {
        return runCatching {
            val arr = JSONObject(body).optJSONArray("tools") ?: JSONArray()
            (0 until arr.length()).mapNotNull { i ->
                val o = arr.optJSONObject(i) ?: return@mapNotNull null
                val name = o.optString("name", "")
                if (name.isBlank()) return@mapNotNull null
                PyTool(
                    name = name,
                    description = o.optString("description", ""),
                    schema = o.optJSONObject("schema") ?: JSONObject(),
                    timeoutSeconds = o.optInt("timeoutSeconds", DEFAULT_TIMEOUT_S),
                    isEnabled = o.optBoolean("isEnabled", true),
                    createdAt = o.optLong("createdAt", 0L),
                    updatedAt = o.optLong("updatedAt", 0L),
                )
            }
        }.getOrElse { emptyList() }
    }

    private fun loadRegistry(context: Context): MutableList<PyTool> {
        val f = registryFile(context)
        if (!f.exists()) return mutableListOf()
        return parseRegistry(f.readText()).toMutableList()
    }

    private fun saveRegistry(context: Context, tools: List<PyTool>) {
        val arr = JSONArray()
        tools.forEach { t ->
            arr.put(
                JSONObject()
                    .put("name", t.name)
                    .put("description", t.description)
                    .put("schema", t.schema)
                    .put("timeoutSeconds", t.timeoutSeconds)
                    .put("isEnabled", t.isEnabled)
                    .put("createdAt", t.createdAt)
                    .put("updatedAt", t.updatedAt),
            )
        }
        registryFile(context).writeText(JSONObject().put("tools", arr).toString(2))
    }

    private fun upsertRegistry(context: Context, tool: PyTool) {
        val all = loadRegistry(context).filter { it.name != tool.name } + tool
        saveRegistry(context, all.sortedBy { it.name })
    }

    private fun removeFromRegistry(context: Context, name: String) {
        saveRegistry(context, loadRegistry(context).filter { it.name != name })
    }

    /** Rescan disk (cheap: one small JSON read) — catches out-of-band registry edits. */
    fun reload() {
        val context = appContext ?: return
        val loaded = loadRegistry(context)
        cache.clear()
        loaded.forEach { cache[it.name] = it }
        _tools.value = loaded
    }

    /** Read the code of one tool (py_meta_tools read action). */
    fun readCode(context: Context, name: String): String? {
        val f = codeFile(context, name.trim())
        if (!f.exists()) return null
        return runCatching { f.readText() }.getOrNull()
    }
}
